"""
SmallBlock UI Constants
"""

UI_VERSION = "0.1.0"

DEFAULT_WINDOW_WIDTH = 640
DEFAULT_WINDOW_HEIGHT = 480

DEFAULT_WIDGET_WIDTH = 100
DEFAULT_WIDGET_HEIGHT = 30

DEFAULT_PADDING = 4
DEFAULT_MARGIN = 2
DEFAULT_SPACING = 4

DEFAULT_FONT = "Default"
DEFAULT_FONT_SIZE = 12

DEFAULT_TITLE = "SmallBlock"

DEFAULT_FPS = 60

ALIGN_LEFT = "left"
ALIGN_CENTER = "center"
ALIGN_RIGHT = "right"

ALIGN_TOP = "top"
ALIGN_MIDDLE = "middle"
ALIGN_BOTTOM = "bottom"

STATE_NORMAL = "normal"
STATE_HOVER = "hover"
STATE_PRESSED = "pressed"
STATE_DISABLED = "disabled"
STATE_FOCUSED = "focused"
